### ISSUE TITLE
error: AttributeError: 'LayerParameter' object has no attribute 'weight_filler'

### ISSUE THREAD

**Issue by hanamizukigakki** [soeaver/caffe-model#3]
i have run the script inception_v1.py and get an error like this:

```
Traceback (most recent call last):
  File "python_googlenet.py", line 435, in <module>
    main()
  File "python_googlenet.py", line 430, in main
    prototxt = inception_v1.inception_v1_proto(batch_size=32)
  File "python_googlenet.py", line 258, in inception_v1_proto
    return n.to_proto()
  File "/home/server/caffe/python/caffe/net_spec.py", line 189, in to_proto
    top._to_proto(layers, names, autonames)
  File "/home/server/caffe/python/caffe/net_spec.py", line 97, in _to_proto
    return self.fn._to_proto(layers, names, autonames)
  File "/home/server/caffe/python/caffe/net_spec.py", line 158, in _to_proto
    assign_proto(layer, k, v)
  File "/home/server/caffe/python/caffe/net_spec.py", line 64, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: 'LayerParameter' object has no attribute 'weight_filler'
```

how can i fix it?

**Comment by lsabrinax** [comment]
I have the same problem.Have you solved it?

**Comment by soeaver** [comment]
I have removed the scripts to generate prototxt, so please use the files which I released here https://github.com/soeaver/caffe-model/tree/master/cls.
